trigada/Trigada/trigada/app/urls.py
from django.urls import path
from . import views

api_urlpatterns = [
    path("api/v1/song_form_success/", views.forms_song_view, name="song_form"),
    path("api/v1/blog_form_success/", views.forms_blog_view, name="blog_form"),
    path("api/v1/anecdote_form_success/", views.anecdote_form_view, name="anecdote_form"),
]

urlpatterns = [
    path("", views.main_view, name='main'),
    path("users/<slug:slug>", views.persons_view, name='users'),
    path("accounts/profile/", views.user_profile, name='profiles'),
    path("videos/", views.presentation_video_view, name='presentation_video'),
    path("all_videos/", views.video_view, name="videos"),
    path("songs/", views.song_view, name='songs'),
    path("tabs/<slug:slug>", views.tab_view, name='tabs'),
    path("musician/<slug:slug>", views.musician_view, name="musicians"),
    path("anecdotes/", views.anecdote_view, name='anecdotes'),
    path("blog/", views.blog_view, name='blogs'),
] + api_urlpatterns

trigada/Trigada/trigada/trigada/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", include('app.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("change-password/", auth_views.PasswordChangeView.as_view(template_name="change-password.html")),
    path("ckeditor/", include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trigada/Trigada/trigada/app/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.shortcuts import render
from . import models
from . import forms


def main_view(request):
    makers = models.Person.objects.all()
    return render(request, template_name="main.html", context={"makers": makers})


def persons_view(request, slug: str):
    makers = models.Person.objects.get(slug=slug)
    return render(request, template_name="makers.html", context={"makers": makers})


@login_required
def user_profile(request):
    profile = models.Person.objects.get(user=request.user)
    form = forms.UploadMusicForm()
    return render(request, template_name="registration/profile.html", context={'profile': profile, 'music_form': form})


@login_required
def anecdote_view(request):
    anecdotes = models.Anecdote.objects.all()
    form = forms.AnecdoteForm()
    context = {"anecdotes": anecdotes, "form": form}
    return render(request, template_name="anecdotes.html", context=context)


@login_required
def presentation_video_view(request):
    video = models.Video.objects.get(title='PRESENTATION')
    return render(request, template_name="presentation_video.html", context={"item": video})


@login_required
def video_view(request):
    videos = models.Video.objects.all()
    return render(request, template_name="videos.html", context={"videos": videos})


def musician_view(request, slug: str):
    context: dict = {}
    try:
        musician = models.Musician.objects.get(slug=slug)
        if musician:
            context['musician'] = musician
            tabs = models.Tab.objects.filter(musician=musician)
            if tabs:
                context['songs'] = tabs
    except ObjectDoesNotExist:
        pass
    return render(request, template_name="musician.html", context=context)


def song_view(request):
    global tabs
    if "query" in request.POST:
        form = forms.SearchTabsForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            tabs = models.Tab.objects.filter(song_name__contains=data['query'])
            if not tabs:
                musician = models.Musician.objects.filter(username__contains=data['query'])
                if musician:
                    tabs = models.Tab.objects.filter(musician=musician[0])
    else:
        form = forms.SearchTabsForm()
        tabs = models.Tab.objects.all()
    return render(request, template_name="songs.html", context={"tabs": tabs, "form": form})


def tab_view(request, slug: str):
    try:
        tab = models.Tab.objects.get(slug=slug)
        context = {'tab': tab}
    except ObjectDoesNotExist:
        context = {}
    return render(request, template_name="tabs.html", context=context)


def blog_view(request):
    blogs = models.Blog.objects.all()
    form = forms.BlogForm()
    return render(request, template_name="blog.html", context={"blogs": blogs, "form": form})


def anecdote_form_view(request):
    context: dict = {}
    if request.method == "POST":
        form = forms.AnecdoteForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            anecdote = models.Anecdote(
                title=data.get('title'),
                text=data.get('text'),
                writer=models.Person.objects.get(user=request.user)
            )
            anecdote.save()
            context['text'] = "Anecdote was added successfully!"
        else:
            context['text'] = "There is some error :("
        context['previous_page'] = request.POST.get("previous_page")
    return render(request, template_name="success_form.html", context=context)


def forms_blog_view(request):
    context: dict = {}
    if request.method == "POST":
        form = forms.BlogForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            blog = models.Blog(
                title=data.get('title'),
                text=data.get('text'),
                user=models.Person.objects.get(user=request.user)
            )
            blog.save()
            context['text'] = "Blog was added successfully!"
        else:
            context['text'] = 'There is some error :('
        context['previous_page'] = request.POST.get("previous_page")
    return render(request, template_name="success_form.html", context=context)


def forms_song_view(request):
    context: dict = {}
    if request.method == "POST":
        form = forms.UploadMusicForm(request.POST, request.FILES)
        if form.is_valid():
            user = models.Person.objects.get(slug=request.POST.get("slug"))
            user.song = request.FILES['song']
            user.save()
            context['text'] = "Song was uploaded successfully!"
        else:
            context['text'] = "There is some error :("
        context['previous_page'] = request.POST.get("previous_page")
    return render(request, template_name="success_form.html", context=context)

trigada/Trigada/trigada/templates/anecdotes.html
{% extends 'layouts/base_layout.html' %}
{% load static %}

{% block title %}
Anecdotes
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/anecdotes.css' %}">
{% endblock %}

{% block wrapper %}
    <div class="anecdotes-head-block transparent">
        <span class="anecdotes-title oxanium transparent">Anecdotes</span>
        <svg id="write-an-anecdote" class="write-anecdote-svg transparent" fill="var(--white)" height="36px" width="36px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 306.637 306.637" xml:space="preserve"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <g> <path d="M12.809,238.52L0,306.637l68.118-12.809l184.277-184.277l-55.309-55.309L12.809,238.52z M60.79,279.943l-41.992,7.896 l7.896-41.992L197.086,75.455l34.096,34.096L60.79,279.943z"></path> <path d="M251.329,0l-41.507,41.507l55.308,55.308l41.507-41.507L251.329,0z M231.035,41.507l20.294-20.294l34.095,34.095 L265.13,75.602L231.035,41.507z"></path> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> </g> </g></svg>
    </div>
    <div class="anecdotes-list transparent">
        {% for anecdote in anecdotes %}
            <div class="anecdote-block transparent">
                <p>{{ anecdote.title }}</p>
                {{ anecdote.text|safe }}
                <p>{{ anecdote.added }}</p>
                <img id="{{ anecdote.writer }}" class="maker-image transparent" src="/media/{{ anecdote.writer.image }}">
            </div>
        {% endfor %}
    </div>
    <form id="anecdote-form" class="form-anecdote hidden transparent" action="{% url 'anecdote_form' %}" method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <input type="hidden" name="previous_page" value="{{ request.path }}">
        <input type="hidden" name="writer" id="id_writer" value="{{ request.user.pk }}">
        <button id="send-anecdote-form" class="send-an-anecdote-form-button transparent" type="submit">Submit!</button>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/anecdotes.js' %}"></script>
    <script src="{% static 'js/to_users.js' %}"></script>
{% endblock %}

trigada/Trigada/trigada/templates/blog.html
{% extends 'layouts/base_layout.html' %}
{% load static %}


{% block title %}
Blog
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock %}

{% block wrapper %}
    <div class="blog-head-block transparent">
        <span class="blog-title oxanium transparent">Blog</span>
        <svg id="write-a-blog" class="write-blog-svg transparent" fill="var(--white)" height="36px" width="36px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 306.637 306.637" xml:space="preserve"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <g> <path d="M12.809,238.52L0,306.637l68.118-12.809l184.277-184.277l-55.309-55.309L12.809,238.52z M60.79,279.943l-41.992,7.896 l7.896-41.992L197.086,75.455l34.096,34.096L60.79,279.943z"></path> <path d="M251.329,0l-41.507,41.507l55.308,55.308l41.507-41.507L251.329,0z M231.035,41.507l20.294-20.294l34.095,34.095 L265.13,75.602L231.035,41.507z"></path> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> </g> </g></svg>
    </div>
    {% if blogs %}
        <div class="block transparent">
            {% for blog in blogs %}
                <div class="blog-block transparent">
                    <span class="blog-name oxanium transparent">{{ blog.title }}</span>
                    <div class="separator transparent"></div>
                    {{ blog.text|safe }}
                    <div class="blog-footer transparent">
                        <span class="date-added oxanium transparent">{{ blog.added }}</span>
                        <img id="{{ blog.user }}" class="maker-image transparent" src="/media/{{ blog.user.image }}">
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <span class="no-blog-error oxanium transparent">No blogs available :(</span>
    {% endif %}
    <form id="blog-form" class="form-blog hidden transparent" action="{% url 'blog_form' %}" method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <input type="hidden" name="previous_page" value="{{ request.path }}">
        <input type="hidden" name="user" id="id_user" value="{{ request.user.pk }}">
        <button id="send-blog-form" class="send-a-blog-form-button transparent" type="submit">Submit!</button>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/to_users.js' %}"></script>
    <script src="{% static 'js/blog.js' %}"></script>
{% endblock %}

trigada/Trigada/trigada/templates/main.html
{% extends 'layouts/base_layout.html' %}
{% load static %}

{% block title %}
TRIGADA
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/main_css.css' %}">
    <link rel="stylesheet" href="{% static 'css/slider.css' %}">
{% endblock %}

{% block wrapper %}
    <p class="page-title oxanium transparent">You are welcome!</p>
	<p class="page-text oxanium transparent">Here is TRIGADA!</p>
	<p class="page-text oxanium transparent">Glad to present it to all of us!</p>
	<p class="page-text oxanium transparent">You can find here guitar tabs (gp format)🎸, interesting blogs (maybe not so interesting)📰, old funny (for us) videos📹, and anecdotes🥸.</p>
	<p class="page-text oxanium transparent">Site was created by us for us. Don't judge the quality 🤍</p>
	<p class="page-subtitle oxanium transparent">official makers</p>
	<div class="section over-hide px-4 px-sm-0 transparent">
		<div class="container transparent">
			<div class="row justify-content-center transparent">
				<div class="col-lg-10 col-xl-8 align-self-center padding-tb transparent">
					<div class="section mx-auto text-center slider-height-padding transparent">
						{% for maker in makers %}
							<style>
								.checkbox#{{ maker.user.username }} + label{
  									background-image: url("media/{{ maker.image }}");
								}
								ul li:nth-child({{ forloop.counter }}) {
									background-image: url("media/{{ maker.image }}");
								}
								.checkbox#{{ maker.user.username }}:checked ~ ul li:nth-child({{ forloop.counter }}) {
									opacity: 1;
									pointer-events: auto;
									border-radius: 16px;
									cursor: pointer;
								}
							</style>
							<input class="checkbox transparent" type="radio" id="{{ maker.user.username }}" name="slider"{% if forloop.first %}checked{% endif %}/>
							<label for="{{ maker.user.username }}"></label>
						{% endfor %}
						<ul>
						{% for maker in makers %}
							<li><span class="comfortaa maker-name transparent">{{ maker.user.username }}</span></li>
						{% endfor %}
						</ul>
				    </div>
			    </div>
	      	</div>
	    </div>
	</div>
{% endblock %}

{% block scripts %}
	<script src="{% static 'js/links_to_users.js' %}"></script>
{% endblock %}

trigada/Trigada/trigada/templates/makers.html
{% extends 'layouts/base_layout.html' %}
{% load static %}

{% block title %}
{{ makers.user.username }}
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/makers.css' %}">
{% endblock %}

{% block wrapper %}
    <div class="maker-block transparent">
        <img class="maker-avatar transparent" src="/media/{{ makers.image }}">
        <div class="maker-information transparent">
            <div class="maker-name-block transparent">
                <p class="maker-fullname comfortaa transparent">{{ makers.user.first_name }} {{makers.user.last_name }}</p>
                <p class="maker-username comfortaa transparent">@{{ makers.user.username }}</p>
            </div>
            <div class="maker-user-info-block transparent">
                <div class="separator transparent"></div>
                <p class="user-info-text comfortaa transparent">Date joined: {{ makers.user.date_joined }}</p>
                <div class="separator transparent"></div>
            </div>
            <div class="buttons-block transparent">
                <a href="/" class="link-style comfortaa transparent">Back to main</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

trigada/Trigada/trigada/templates/musician.html
{% extends 'layouts/base_layout.html' %}
{% load static %}

{% block title %}
{{ musician.username }}
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/musician.css' %}">
{% endblock %}

{% block wrapper %}
    {% if musician %}
        <div class="image transparent" style="width: 400px; height: 400px; border-radius: 200px; background-image: url(/media/{{ musician.image }}); background-size: cover;">
<!--            <img class="musician-image transparent" src="/media/{{ musician.image }}">-->
        </div>
        <span class="musician-username oxanium transparent">{{ musician.username }}</span>
        <span class="musician-text oxanium transparent">{{ musician.first_name }} {{ musician.last_name }}</span>
        {% if songs %}
            <span class="songs-list-title oxanium transparent">Songs</span>
            <div class="songs-list transparent">
                {% for song in songs %}
                    <a class="song-text oxanium transparent" href="/tabs/{{ song.slug }}">{{ song.song_name }}</a>
                {% endfor %}
            </div>
        {% endif %}
    {% else %}
        <span class="musician-username oxanium transparent">There is no such a musician 😞</span>
    {% endif %}
{% endblock %}

{% block scripts %}
{% endblock %}

trigada/Trigada/trigada/templates/presentation_video.html
{% extends 'layouts/base_layout.html' %}
{% load static %}


{% block title %}
PRESENTATION
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/presentation_video.css' %}">
{% endblock %}

{% block wrapper %}
    <span class="presentation-title honk transparent">PRESENTATION</span>
    <div class="presentation-block transparent">
        <video class="main-video-border" id="main-video" poster="{% static 'img/poster/presentation-poster.png' %}" controls width="100%" height="480" controlsList="nodownload" oncontextmenu="return false;">
            <source src="{% static 'video/presentation.webm' %}" type="video/webm" />
        </video>
    </div>
    <a href="/all_videos/" class="video-buttons honk transparent">Much more videos!</a>
    <video class="background-video" muted autoplay loop>
        <source src="{% static 'video/presentation.webm' %}" type="video/webm">
    </video>
{% endblock %}

{% block scripts %}
    <script>
        const video = document.getElementById('main-video');
        video.addEventListener('fullscreenchange', function() {
             video.classList.toggle('main-video-border');
        });
    </script>
    <script src="{% static 'js/to_users.js' %}"></script>
{% endblock %}

trigada/Trigada/trigada/templates/songs.html
{% extends 'layouts/base_layout.html' %}
{% load static %}

{% block title %}
Guitar Pro Tabs
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/songs.css' %}">
{% endblock %}

{% block wrapper %}
    {% if form.errors %}
        <p class="login-error oxanium transparent">Your username and password didn't match. Please try again.</p>
    {% endif %}
    <form class="search-form transparent" action="{% url 'songs' %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <label class="form-label oxanium transparent" for="{{ field.auto_id }}"></label>
            {{ field }}
        {% endfor %}
        <button class="search-button oxanium transparent" type="submit">Search</button>
    </form>
    <span class="notification oxanium transparent">So far, the search is only possible by the nickname of the musician or by the name of the song. Sorry 😔</span>
    {% if tabs %}
        <div class="music-list transparent">
        {% for tab in tabs %}
            <div class="song-block transparent">
                <img class="musician-image transparent" src="/media/{{ tab.musician.image }}">
                <a class="musician-link oxanium transparent" href="/musician/{{ tab.musician.slug }}">{{ tab.musician }}</a>
                <span class="dash oxanium transparent">&nbsp;–&nbsp;</span>
                <a class="song-link oxanium transparent" href="/tabs/{{ tab.slug }}">{{ tab.song_name }}</a>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <span class="music-error-text oxanium transparent">There is no such songs or musicians 😞</span>
    {% endif %}
{% endblock %}

{% block scripts %}
{% endblock %}

trigada/Trigada/trigada/templates/success_form.html
{% extends 'layouts/base_layout.html' %}
{% load static %}

{% block title %}
Completed!
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/success_form.css' %}">
{% endblock %}

{% block wrapper %}
    <span class="success-form-title oxanium transparent">{{ text }}</span>
    <a class="success-form-text oxanium transparent" href="{{ previous_page }}">Back to previous page!</a>
{% endblock %}

{% block scripts %}
{% endblock %}

trigada/Trigada/trigada/templates/tabs.html
{% extends 'layouts/base_layout.html' %}
{% load static %}

{% block title %}
    {{ tab.musician.username }} - {{ tab.song_name }}
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/tabs.css' %}">
{% endblock %}

{% block wrapper %}
    <span class="tab-title oxanium transparent">{{ tab.musician.username }} - {{ tab.song_name }}</span>
    <div class="transparent">
        <div class="download-block transparent">
            <img class="guitar-pro-icon transparent" src="{% static 'img/guitar-pro-logo.png' %}">
            <div class="file-name oxanium transparent">
                <span class="file-name-text oxanium transparent">{% for filename in tab.get_filename %}{{ filename }}{% endfor %}</span>
                <a class='download-text oxanium transparent' href="/media/{{ tab.file }}">Download</a>
            </div>
        </div>
        <div class="information-block transparent">
            <div class="information-text-block transparent">
                <span class="info-text oxanium transparent">Album: </span>
                <span class="info-text-value oxanium transparent">{{ tab.album }}</span>
            </div>
            <div class="information-text-block transparent">
                <span class="info-text oxanium transparent">Year: </span>
                <span class="info-text-value oxanium transparent">{{ tab.year }}</span>
            </div>
            {% if tab.comments %}
                <span class="info-text oxanium transaprent">Comments: </span>
                <span class="info-text-value oxanium transparent">{{ tab.comments }}</span>
            {% endif %}
            <div class="information-text-block transparent">
                <span class="info-text oxanium transparent">Contributed: </span>
                {% for user in tab.users.all %}
                    <img id="{{ user.slug }}" class="maker-image oxanium transparent" src="/media/{{ user.image }}">
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/to_users.js' %}"></script>
{% endblock %}

trigada/Trigada/trigada/templates/videos.html
{% extends 'layouts/base_layout.html' %}
{% load static %}
{% load embed_video_tags %}

{% block title %}
VIDEOS
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/videos.css' %}">
{% endblock %}

{% block wrapper %}
    <p class="video-title oxanium transparent">Videos</p>
    <div class="videos-content-main transparent">
        {% for item in videos|slice:":3" %}
            <div class="video-block transparent">
                {% video item.url '360x250' %}
                <p class="video-text oxanium transparent">{{ item.title }}</p>
                <div class="maker-avatars-wrapper transparent">
                    <p class="video-text-creators oxanium transparent">Contributed: </p>
                    <div class="maker-avatars transparent">
                        {% for user in item.users.all %}
                            <img id="{{ user.user.username }}" class="maker-image transparent" src="/media/{{ user.image }}">
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="video-separator"></div>
    <div class="videos-content-second transparent">
        {% for item in videos|slice:"3:" %}
            <div class="video-block transparent">
                {% video item.url '315x200' %}
                <p class="video-text oxanium transparent">{{ item.title }}</p>
                <div class="maker-avatars-wrapper transparent">
                    <p class="video-text-creators oxanium transparent">Contributed: </p>
                    <div class="maker-avatars transparent">
                        {% for user in item.users.all %}
                            <img id="{{ user.user.username }}" class="maker-image transparent" src="/media/{{ user.image }}">
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/to_users.js' %}"></script>
{% endblock %}